general:
  pipelineVersion: "2.0"
stages:
  Upload:
    enabled: true
    # Instructs the 2.0 engine to unpack the zip archive before evaluation
    unpack: true
    sapCPILint:
      enabled: true
      rulesFile: "cpilint-rules.xml"
  Deploy:
    enabled: true
  'Integration Test':
    enabled: false
